import { expect, test } from '@playwright/test'

const fixture = '/tests/fixtures/account.html'

test('the name opens account details; signing out requires its own action', async ({ page }) => {
  await page.goto(fixture)
  const trigger = page.getByRole('button', { name: 'Account menu for Matt' })
  await expect(page.getByRole('link', { name: 'Create evaluation' })).toHaveAttribute('href', '/evaluations')
  await trigger.click()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.account-email')).toHaveText('matt@example.invalid')
  await expect(page.getByLabel('Sign-out attempts')).toHaveText('0')
  await expect(page.getByRole('menuitem', { name: 'Evaluations' })).toHaveAttribute('href', '/evaluations')
  await expect(page.getByRole('menuitem', { name: 'Studio', exact: true })).toHaveAttribute('href', '/studio')
  await expect(page.getByRole('menuitem', { name: 'Report library' })).toHaveAttribute('href', '/reports')
  await expect(page.getByRole('menuitem', { name: 'Runner setup' })).toHaveAttribute('href', '/machines')
  await expect(page.getByRole('menuitem', { name: 'Set up a computer' })).toHaveAttribute('href', '/machines?setup=1')
  await trigger.click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await trigger.click()
  await page.getByRole('menuitem', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await expect(page.getByLabel('Sign-out attempts')).toHaveText('1')
  await expect(page.getByRole('menu')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Create evaluation' })).toHaveCount(0)
})

test('supports keyboard navigation, dismissal, and focus return', async ({ page }) => {
  await page.goto(fixture)
  const trigger = page.getByRole('button', { name: 'Account menu for Matt' })
  await trigger.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Evaluations' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Studio', exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByRole('menuitem', { name: 'Sign out', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.keyboard.press('ArrowUp')
  await expect(page.getByRole('menuitem', { name: 'Sign out', exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page.getByRole('menuitem', { name: 'Evaluations' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Outside control' })).toBeFocused()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await trigger.click()
  await page.getByRole('link', { name: 'heval', exact: true }).click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await expect(page.getByLabel('Sign-out attempts')).toHaveText('0')
})

test('waits for session verification and only offers sign-in to guests', async ({ page }) => {
  await page.goto(fixture + '?session=loading')
  await expect(page.locator('.account-controls').getByRole('status')).toHaveText('Checking account…')
  await expect(page.getByRole('button', { name: /Sign in|Account menu/ })).toHaveCount(0)
  await page.goto(fixture + '?session=unconfigured')
  await expect(page.locator('.account-controls')).toHaveCount(0)
  await page.goto(fixture + '?session=guest')
  await expect(page.getByRole('link', { name: 'Create evaluation' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Account menu for Matt' })).toBeVisible()
})

test('authentication errors allow retry without misrepresenting the session', async ({ page }) => {
  await page.goto(fixture + '?error=1')
  await page.getByRole('button', { name: 'Account menu for Matt' }).click()
  await page.getByRole('menuitem', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Couldn’t sign out. Please try again.')
  await expect(page.getByRole('menuitem', { name: 'Sign out', exact: true })).toBeEnabled()
  await expect(page.locator('.account-email')).toHaveText('matt@example.invalid')
  await page.goto(fixture + '?session=guest&error=1')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Couldn’t open sign-in. Please try again.')
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeEnabled()
})

test('the whole menu remains usable outside a scrolling toolbar', async ({ page }) => {
  await page.goto(fixture + '?overflow=1')
  await page.getByRole('button', { name: 'Account menu for Matt' }).click()
  const menu = page.locator('.account-menu')
  await expect(menu).toBeVisible()
  const bounds = await menu.boundingBox()
  const viewport = page.viewportSize()!
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height)
  await page.getByRole('menuitem', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
})
