import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('autoplays and loops standalone panes with header metrics', async ({ page }) => {
  test.setTimeout(60_000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const demo = page.getByRole('group', { name: 'Scripted coding-agent demo' })
  await expect(demo.locator('.lane-state.ready')).toHaveCount(4)
  await page.clock.install({ time: new Date('2026-09-16T12:00:00Z') })
  await page.clock.pauseAt(new Date('2026-09-16T12:00:01Z'))
  await demo.evaluate(element => element.scrollIntoView({ behavior: 'instant', block: 'start' }))
  await expect(demo).toBeInViewport()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(demo.locator('.runner-lane')).toHaveCount(4)
  await expect(demo.locator('.lane-head .lane-stats')).toHaveCount(4)
  await expect(demo.locator('.runner-lane > .lane-stats')).toHaveCount(0)
  await expect(page.locator('.race-toolbar, .race-shell, .task-strip, .playback, .race-verdict, .lane-progress')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Play replay|Pause replay|^Replay$/ })).toHaveCount(0)
  await page.clock.runFor(3000)
  const elapsed = demo.locator('.lane-elapsed').first()
  await expect.poll(async () => parseInt(await elapsed.innerText())).toBeGreaterThan(0)
  await page.clock.runFor(18000)
  await expect(demo.locator('.lane-state.passed')).toHaveCount(4)
  await expect(elapsed).toHaveText('40s')
  await page.clock.runFor(3500)
  await expect(demo.locator('.lane-state.running')).toHaveCount(4)
  await expect.poll(async () => parseInt(await elapsed.innerText())).toBeLessThan(40)

  await page.locator('.footer').evaluate(element => element.scrollIntoView({ behavior: 'instant', block: 'start' }))
  await expect(demo).not.toBeInViewport()
  await page.clock.runFor(300)
  const paused = await elapsed.innerText()
  await page.clock.runFor(4000)
  await expect(elapsed).toHaveText(paused)
  await demo.evaluate(element => element.scrollIntoView({ behavior: 'instant', block: 'start' }))
  await expect(demo).toBeInViewport()
  await page.clock.runFor(3000)
  await expect(elapsed).not.toHaveText(paused)
})

test('focuses a runner and submits an early-access signup', async ({ page }) => {
  const lane = page.locator('.runner-lane').filter({ hasText: 'OpenCode' })
  await lane.click()
  await expect(lane).toHaveClass(/focused/)

  await page.route('**/api/signups', async route => {
    expect(route.request().postDataJSON()).toEqual({ email: 'dev@example.com', consent: true })
    await route.fulfill({ status: 201, json: { ok: true } })
  })
  await page.getByLabel('I agree to receive Heval project updates by email.').check()
  await page.getByPlaceholder('you@company.com').fill('dev@example.com')
  await page.getByRole('button', { name: /get early access/i }).last().click()
  await expect(page.getByText('You’re on the list.')).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('heval:preferences'))).toBeNull()
})

test('keeps the showcase public while real runs require authentication', async ({ page }) => {
  await expect(page.getByRole('heading', { name: 'The open-source evaluation platform for coding agents.', exact: true })).toBeVisible()
  page.once('dialog', async (dialog) => {
    expect(dialog.message()).toContain('WorkOS AuthKit')
    await dialog.dismiss()
  })
  await page.getByRole('button', { name: 'RUN REAL' }).first().click()
})

test('shows the GitHub link in the simplified navigation', async ({ page }) => {
  const nav = page.getByRole('navigation')
  const github = nav.getByRole('link', { name: 'GitHub', exact: true })
  await expect(github).toBeVisible()
  await expect(github).toHaveAttribute('href', 'https://github.com/MatthewFeroz/heval')
  await expect(github).toHaveAttribute('target', '_blank')
  await expect(nav.getByRole('link', { name: /^(Replay|Reports|Methodology|Studio|Your reports|Machines & runs)$/ })).toHaveCount(0)
})

test('shows the product entry point and measured evaluation preview', async ({ page }) => {
  await expect(page.locator('.nav .brand')).toHaveText('heval')
  await expect(page.locator('.hero-harness')).toHaveCount(9)
  await expect(page.locator('.hero-harnesses').getByRole('link')).toHaveCount(0)
  await expect(page.locator('.hero-harnesses').getByRole('img', { name: 'Deep Agents' })).toBeVisible()
  await expect(page.locator('.hero-harnesses').getByRole('img', { name: 'Antigravity' })).toBeVisible()
  await expect(page.locator('.hero-harnesses').getByRole('img', { name: 'Grok' })).toBeVisible()
  await expect(page.locator('.hero-harnesses').getByRole('img', { name: 'Cursor', exact: true })).toBeVisible()
  await expect(page.locator('.hero-copy')).toContainText('Compare Claude Code')
  await expect(page.locator('.hero-copy')).toContainText('with Harbor. Inspect every trial.')
  await expect(page.locator('.hero-harnesses')).toHaveText('')
  await expect(page.locator('.hero-harnesses').getByRole('img', { name: /Hermes|Goose|OpenHands|Gemini CLI/ })).toHaveCount(0)
  await expect(page.locator('main > section').nth(1)).toHaveAttribute('id', 'compare')
  await expect(page.locator('main > section').nth(2)).toHaveClass(/studio-showcase/)
  const start = page.getByRole('link', { name: 'Create an evaluation', exact: true })
  await expect(start).toHaveAttribute('href', '/evaluations')
  await expect(page.getByRole('link', { name: 'Explore an example', exact: true })).toHaveAttribute('href', '/evaluations#example')
  const github = page.getByRole('link', { name: 'Explore the code on GitHub' })
  await expect(github).toHaveAttribute('href', 'https://github.com/MatthewFeroz/heval')
  const startBox = await start.boundingBox()
  const githubBox = await github.boundingBox()
  expect(githubBox!.y).toBeGreaterThan(startBox!.y + startBox!.height)
  await expect(page.locator('.completion-row')).toHaveCount(6)
  await expect(page.locator('.evaluation-stats')).toContainText('Trials120')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await page.locator('.hero-harness').first().evaluate((el) => parseFloat(getComputedStyle(el).animationDuration))).toBeLessThan(.001)
  await expect(page.getByRole('heading', { name: 'See how a replay works.' })).toHaveCount(0)
  const deepAgents = await page.locator('.hf-deep-agents').boundingBox()
  const openCode = await page.locator('.hf-opencode').boundingBox()
  const headline = await page.locator('#hero-title').boundingBox()
  const connect = await page.locator('.hero-links').boundingBox()
  const demo = await page.locator('.replay-demo').boundingBox()
  const viewport = page.viewportSize()!
  const marks = await page.locator('.hero-float-mark').evaluateAll(elements => elements.map(element => {
    const box = element.getBoundingClientRect()
    return { width: box.width, height: box.height, top: box.top, center: box.x + box.width / 2 }
  }))
  expect(new Set(marks.map(mark => `${mark.width}x${mark.height}`)).size).toBe(1)
  expect(marks.every(mark => mark.top >= 0)).toBe(true)
  expect(Math.abs(marks.reduce((sum, mark) => sum + mark.center, 0) / marks.length - viewport.width / 2)).toBeLessThan(2)
  const headerStyle = await page.locator('.site-header').evaluate(element => ({ position: getComputedStyle(element).position, background: getComputedStyle(element).backgroundColor }))
  expect(headerStyle).toEqual({ position: 'absolute', background: 'rgba(0, 0, 0, 0)' })
  await expect(page.locator('.hero-copy > span')).toHaveCount(2)
  if (viewport.width > 1180) expect(await page.locator('.hero-copy').evaluate(element => {
    const lineHeight = parseFloat(getComputedStyle(element).lineHeight)
    return element.scrollHeight > lineHeight * 1.9 && element.scrollHeight <= lineHeight * 2.1
  })).toBe(true)
  expect(deepAgents!.y + deepAgents!.height).toBeLessThan(headline!.y)
  if (viewport.width > 1180) expect(headline!.y - (deepAgents!.y + deepAgents!.height)).toBeLessThanOrEqual(40)
  if (viewport.width > 820) expect(openCode!.y - deepAgents!.y).toBeGreaterThan(150)
  expect(demo!.y - (connect!.y + connect!.height)).toBeGreaterThanOrEqual(0)
  expect(demo!.y - (connect!.y + connect!.height)).toBeLessThanOrEqual(32)
  const previewWidth = viewport.width <= 960 ? Math.min(860, viewport.width - 24) : Math.min(1176, viewport.width - 64)
  expect(demo!.width).toBeCloseTo(previewWidth, 0)
  expect(demo!.x).toBeCloseTo((viewport.width - previewWidth) / 2, 0)
  expect(demo!.y).toBeLessThan(viewport.height - 100)
  await start.click()
  await expect(page).toHaveURL(/\/evaluations$/)
  await expect(page.getByRole('heading', { name: /Create an evaluation|Evaluations are coming online/ })).toBeVisible()
})

test('signup failure does not claim the email was saved', async ({ page }) => {
  await page.route('**/api/signups', route => route.fulfill({ status: 503, json: { error: 'Could not save your signup. Please retry.' } }))
  await page.getByPlaceholder('you@company.com').fill('dev@example.com')
  await page.getByLabel('I agree to receive Heval project updates by email.').check()
  await page.getByRole('button', { name: /get early access/i }).last().click()
  await expect(page.getByRole('alert')).toContainText('Could not save')
  await expect(page.getByText('You’re on the list.')).toHaveCount(0)
})

// Resizing and focusing must change the terminal grid, not crop a fixed 96-column screen.
test('fits native startup terminals and preserves replay after resizing', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.install()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.model-row')).toHaveCount(0)
  await expect(page.locator('.lane-state.ready')).toHaveCount(4)
  await expect(page.getByRole('img', { name: /startup terminal$/ })).toHaveCount(4)
  await expect(page.locator('.runner-lane').nth(0).locator('.xterm-rows')).toContainText('Try "refactor <filepath>"')
  await expect(page.locator('.runner-lane').nth(1).locator('.xterm-rows')).toContainText('Ask Codex to do anything')
  await expect(page.locator('.runner-lane').nth(2).locator('.xterm-rows')).toContainText('Ask anything')
  await expect(page.locator('.runner-lane').nth(3).locator('.xterm-rows')).toContainText('Pi can explain its own features')
  const fits = async () => page.locator('.real-terminal').evaluateAll(elements => elements.every(element => {
    if (!element.clientWidth) return true
    const screen = element.querySelector<HTMLElement>('.xterm-screen')!
    const style = getComputedStyle(element)
    return screen.offsetWidth <= element.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight) + 1
      && screen.offsetHeight <= element.clientHeight - parseFloat(style.paddingTop) - parseFloat(style.paddingBottom) + 1
  }))
  for (const width of [1440, 1024, 960, 820, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(fits).toBe(true)
    expect(await page.locator('.lane-head').evaluateAll(headers => headers.every(header => header.scrollWidth <= header.clientWidth))).toBe(true)
    const expectedWidth = width <= 960 ? Math.min(860, width - 24) : Math.min(1176, width - 64)
    const panel = await page.locator('.replay-demo').boundingBox()
    expect(panel!.width).toBeCloseTo(expectedWidth, 0)
    expect(panel!.x).toBeCloseTo((width - expectedWidth) / 2, 0)
  }
  const lane = page.locator('.runner-lane').filter({ hasText: 'OpenCode' })
  await lane.click()
  await expect(lane).toHaveClass(/focused/)
  await expect.poll(fits).toBe(true)
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.clock.runFor(6000)
  await expect(lane.getByRole('img', { name: 'OpenCode terminal replay' })).toBeVisible()
  await expect(lane.locator('.xterm-rows')).toContainText('Running all tests')
  await expect.poll(fits).toBe(true)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.clock.runFor(1000)
  await expect(page.locator('.lane-state.ready')).toHaveCount(4)
  await expect(lane.locator('.xterm-rows')).toContainText('Ask anything')
  await page.goto('/reports')
  expect(errors).toEqual([])
})
